### ISSUE TITLE
Chosen filenames prevent importing

### ISSUE THREAD

**Issue by 42B** [ncorbuk/SubZone#1]
```python
>>> import subzone_v1.0
  File "<input>", line 1
    import subzone_v1.0
                      ^
SyntaxError: invalid syntax

```

**Comment by ncorbuk** [comment]
use subzone v2.0

**Comment by ncorbuk** [comment]
your using the wrong one sorry, that one is broken i thought i removed it

**Comment by ncorbuk** [comment]
fork it again and use v2 my friend all is working

**Comment by 42B** [comment]
@ncorbuk 

You aren't understanding the issue, the exact same problem persists if I wanted to import version 2 from another python script.

**Comment by ncorbuk** [comment]
oh i see i will look into this... do you know why the filenames are preventing by any chance?

**Comment by ncorbuk** [comment]
oh yea i see lol will fix now.

**Comment by 42B** [comment]
@ncorbuk 

I gave you an example...

If you wanted my suggestion, I would potentially delete version 1 and rename version 2 something like `subzone.py`. Having version numbers in the filename is odd.

**Comment by ncorbuk** [comment]
Yes sorry you did, have just done that now... thanks for your input i never thought about the version number in filename etc causing a problem. thanks :)

**Comment by 42B** [comment]
@ncorbuk 

No problem, just saw your post on reddit and thought I'd take a look through your project!

**Comment by ncorbuk** [comment]
ah i see, i thought so haha thanks been a great help seems i had bugs i did not know about! will look into the rest buddy 👍 going to close this now, another tick off the list ha!
