### ISSUE TITLE
Use `sys.exit` instead of `exit`

### ISSUE THREAD

**Issue by 42B** [ncorbuk/SubZone#10]
https://github.com/ncorbuk/SubZone/blob/71dfa0e6b6bfd143a848387d937f4d0d61aec94f/subzone.py#L125

> The site module (which is imported automatically during startup, except if the -S command-line option is given) adds several constants to the built-in namespace. ***They are useful for the interactive interpreter shell and should not be used in programs.***

* https://docs.python.org/3/library/constants.html?highlight=exit#constants-added-by-the-site-module

* https://docs.python.org/3/library/sys.html#sys.exit

**Comment by ncorbuk** [comment]
Yep thanks changed it now

**Comment by 42B** [comment]
You should really work on writing proper commit messages. Using the same phrase over and over is not descriptive at all.

Plus, you can close these issues automatically as part of the commit message instead of always having to manually do it.

* https://help.github.com/articles/closing-issues-using-keywords/
