### ISSUE TITLE
Unnecessary function?

### ISSUE THREAD

**Issue by 42B** [ncorbuk/SubZone#2]
https://github.com/ncorbuk/SubZone/blob/abcaf21b6a9473cf80cfafe5824180c71b2efa7d/subzone_v2.0.py#L93-L107

Why not just use `pip install -r requirements.txt` and/or `setup.py` beforehand?

* https://packaging.python.org/

**Comment by ncorbuk** [comment]
Because if someone do not have pip, then it would not do anything? so i thought its best/easiest to just check and if they do not have requirements they can install them there self?

**Comment by 42B** [comment]
Why wouldn't they have pip... it comes with Python?

**Comment by 42B** [comment]
The goal should be to make a python package so people could simply type `pip install subzone` and have everything installed in one shot.

**Comment by ncorbuk** [comment]
ah i see i read somewhere they not everyone had the easy install setup maybe i read something posted from years ago, ill change that. thanks for letting me know

**Comment by 42B** [comment]
No problem. Ya, if you are using fstrings that means people must be using Python 3.6+ so pip should come with it.

**Comment by ncorbuk** [comment]
Whats your name on reddit bro maybe ill see you around, am new to the place looks interesting tho :)

**Comment by ncorbuk** [comment]
fixed now, included a pip install if false on any of requirements... so is more useful then it was.

**Comment by 42B** [comment]
Again, you aren't understanding the issue. This function shouldn't be in your file at all.

**Comment by ncorbuk** [comment]
oh i see a python package, pip install subzone any idea on how? as i really have no idea ive only ever seen people use requirements.txt etc. I'm going do some googling see what come up

**Comment by 42B** [comment]
@ncorbuk 

> Any idea on how i would go about this?

Hmm... maybe the link I provided in the description of this issue?

**Comment by ncorbuk** [comment]
Ok will have a look, am near i done pip install . and it said it created distro but only has subzone-2.0.dist-info folder not another folder with py file in, and says no subzone when i try to import..obv something wrong, ill check your link out now

**Comment by ncorbuk** [comment]
Yep i have done it! only took a few hours haha. thank! learnt something i never knew pretty good, altho my crapy windows was putting files in c drive when im in d and stuff adding to path wouldnt work and had to use full path...basically just complicated things lol.

**Comment by ncorbuk** [comment]
now twine works. without full path, new a reset of cmd would do it.. lol. 👍

**Comment by 42B** [comment]
@ncorbuk 

I have no idea what you are referring to, I don't see a `setup.py` file in your repo and the last commit was 3 hours ago.

**Comment by 42B** [comment]
@ncorbuk 

You are missing out one of the most important steps which are clearly shown in the tutorials I linked to. Even if someone can use `pip install subzone`, you are forcing them to have to then type `pip install -r requirements.txt`. If you added a proper `setup.py` file, `pip install subzone` would take care of that in one shot. You're almost there...

**Comment by ncorbuk** [comment]
oh shit i did do a proper setup.py file i just forgot to delete the requirements function. damit

**Comment by ncorbuk** [comment]
wouldn't keeping the requirements in there be ok for people that didn't use pip to install it and forked it or whatever?

**Comment by 42B** [comment]
@ncorbuk 

I didn't say delete `requirements.txt` at all.

Good luck with your project but I don't have time to keep answering things which are easily google-able.

**Comment by ncorbuk** [comment]
ok, thanks for your feedback it has helped me immensely.
