### ISSUE TITLE
NameError/UnboundLocalError?

### ISSUE THREAD

**Issue by 42B** [ncorbuk/SubZone#3]
https://github.com/ncorbuk/SubZone/blob/abcaf21b6a9473cf80cfafe5824180c71b2efa7d/subzone_v2.0.py#L120-L127

```python
>>> def parse_url():
...     try:
...         host = {}['unknown key']
...     except Exception as e:
...         print('parse_url//Error: %s' % (e))
...         pass
...     return host
... 
>>> parse_url()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 7, in parse_url
UnboundLocalError: local variable 'host' referenced before assignment
parse_url//Error: 'unknown key'

>>> try:
...     host = {}['unknown key']
... except Exception as e:
...     print('parse_url//Error: %s' % (e))
...     pass
... print(host)
Traceback (most recent call last):
  File "<input>", line 6, in <module>
NameError: name 'host' is not defined
parse_url//Error: 'unknown key'
```

**Comment by ncorbuk** [comment]
Uhm dont get this, so that means you cant run the program?? ive just ran it and got all facebook subdomains etc?

**Comment by ncorbuk** [comment]
no errors or anything

**Comment by 42B** [comment]
Try an invalid domain...

**Comment by ncorbuk** [comment]
when you say invalid domain can you give me an example

**Comment by ncorbuk** [comment]
def parse_url(self):
		#parse host from scheme, to use for certificate transparency abuse
		try:
			host = urllib3.util.url.parse_url(self.domain).host
		except Exception as e:
			print(f'Invalid - Domain, try again...')
			exit(1)
		return host

**Comment by ncorbuk** [comment]
Just did that if its invalid then tell them exit for them to try again, so i guess its fixed

**Comment by 42B** [comment]
Tabs still?

**Comment by 42B** [comment]
https://docs.python.org/3/library/urllib.parse.html
