### ISSUE TITLE
Use spaces instead of tabs for indentation

### ISSUE THREAD

**Issue by 42B** [ncorbuk/SubZone#5]
https://pep8.org/#tabs-or-spaces

**Comment by ncorbuk** [comment]
Yep your so rite about this, and i knew this too :( i hate spaces so slow lol, but... will change it as mess's up code/pulls with other people adding code etc in future/future projects. Will fix soon.

**Comment by 42B** [comment]
@ncorbuk 

How are they slow? I use the tab key all the time... and it writes 4 spaces each time.

**Comment by ncorbuk** [comment]
yea you just said write tabs or spaces? i tab 4 spaces each time too? it is fast pressing the space bar is slow lol, tabbing is not the same as pressing space bar 4 times which is what you were saying i should use 4 spaces? tab is ---- and spaces is .... if you select over code that has both you'll see what i mean, and using tabs(which i have used in this and use) is bad and not pep8 and makes code that is written with spaces(....) not compatible eg. if anyone wants to pull in future and add code to project it becomes a mess

**Comment by 42B** [comment]
> i tab 4 spaces each time too?

Nope, you are putting a tab character each time,`'\t'`. I have no clue what kind of text editor you are using but, for example, PyCharm simply types 4 spaces every single time you hit the tab key. Sublime text, vs-code or whatever can all usually be set to write four spaces each time the tab key is hit.

**Comment by ncorbuk** [comment]
Oh i see, im using sublime text and each time i press tab i indents 4 spaces but its not a space... if i mix tabs and space's i get errors. Ill definitely look in too that, be real handy i can imagine.

**Comment by 42B** [comment]
`translate_tabs_to_spaces`

* https://www.sublimetext.com/docs/3/indentation.html

**Comment by ncorbuk** [comment]
ah! thanks nice,

**Comment by ncorbuk** [comment]
changed the settings it did nothing, went in indentation menu and there is a setting convert indentation to tabs & convert indentation to spaces, clicked spaces... now i get spaces with tab! v nice ha, nice tip. 🥇 

closing topic now.
