### ISSUE TITLE
Unnecessary requirement?

### ISSUE THREAD

**Issue by 42B** [ncorbuk/SubZone#6]
https://github.com/ncorbuk/SubZone/blob/abcaf21b6a9473cf80cfafe5824180c71b2efa7d/requirements.txt#L3

`json` is in the standard library?

* https://docs.python.org/3/library/json.html

**Comment by ncorbuk** [comment]
Yes your correct, my bad. Have fixed that now.

thank you.

**Comment by 42B** [comment]
@ncorbuk 

`argparse` and `urllib3` too...
