### ISSUE TITLE
Reopening an open file?

### ISSUE THREAD

**Issue by 42B** [ncorbuk/SubZone#7]
https://github.com/ncorbuk/SubZone/blob/9609f13a4de4ba5253efa23f3f81756f0522cd91/subzone.py#L237-L245

The second context manager is opening the same file which hasn't been closed by the first one?

**Comment by ncorbuk** [comment]
yea one is write to write the contents of cmd = subprocess.call and the other is to read the file. Ive seen you issue above about this too and will sort it now
