### ISSUE TITLE
More unnecessary requirements...

### ISSUE THREAD

**Issue by 42B** [ncorbuk/SubZone#8]
https://github.com/ncorbuk/SubZone/blob/9609f13a4de4ba5253efa23f3f81756f0522cd91/requirements.txt#L3-L4

**Comment by ncorbuk** [comment]
Don't think urllib3 is in the standard library _urllib3 brings many critical features that are missing from the Python standard libraries: ..._ from the urllib3 site. Will remove the argparse library tho.

**Comment by ncorbuk** [comment]
have fixed it, thanks

**Comment by 42B** [comment]
What makes you think you can't parse a url with Python's standard library?

* https://docs.python.org/3/library/urllib.parse.html
